Blog.Web/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.Data.Models;
using Microsoft.AspNetCore.Mvc;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using Blog.Web.ViewModels;

namespace Blog.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class AdminController : Controller
    {
        private BlogDbContext _blogContext;
        private IMapper _mapper;

        public AdminController(BlogDbContext blogContext, IMapper mapper)
        {
            _blogContext = blogContext;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            return View(new Admin());
        }


    }
}

Blog.Web/Views/Shared/Layouts/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <partial name="_DefaultHead" />

</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark ">

        <div class="container px-4">
            @*https://getbootstrap.com/docs/4.0/components/navbar/#containers*@


            <a asp-controller="Home" asp-action="Index" class="navbar-brand font-weight-bold">Solores Software</a>

            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                }
                else
                {
                    <environment include="Development">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        </ul>
                    </environment>
                }
            </div>
        </div>
    </nav>

    <div class="container">

        <div class="row">
            <div class="col-12">
                @RenderBody()
            </div>
        </div>
        <hr />
        <footer>
            @RenderSection("Footer", required: false)

            <div class="text-center">
                <p>&copy; @DateTime.Now.Year - Solores Software</p>
            </div>
        </footer>
    </div>

    <partial name="_DefaultScripts" />

    @RenderSection("Scripts", required: false)

    @Html.RenderPartialViewScripts();

</body>
</html>

Blog.Web/Views/Shared/Layouts/_DefaultLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <partial name="_DefaultHead" />

</head>
<body>

    <nav class="navbar navbar-expand-sm bg-dark ">

        <div class="container px-4">
            @*https://getbootstrap.com/docs/4.0/components/navbar/#containers*@


            <a asp-controller="Home" asp-action="Index" class="navbar-brand font-weight-bold">Solores Software</a>

            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a asp-controller="Account" asp-action="SignOut">Sign Out</a>
                        </li>
                    </ul>
                }
                else
                {
                    <environment include="Development">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item">
                                <a asp-controller="Admin" asp-action="Index">Admin</a>
                            </li>
                        </ul>
                    </environment>
                }
            </div>
        </div>
    </nav>

    <div class="container">



        <div class="row">
            <div class="col-md-9 col-xs-12">
                @RenderBody()
            </div>
            <div class="col-md-3 col-xs-12">
                <partial name="_Sidebar" />

            </div>
        </div>
        <hr />
        <footer>
            @RenderSection("Footer", required: false)

            <div class="text-center">
                <p>&copy; @DateTime.Now.Year - Solores Software</p>
            </div>
        </footer>
    </div>

    <partial name="_DefaultScripts" />

    @RenderSection("Scripts", required: false)

    @Html.RenderPartialViewScripts();

</body>
</html>

Blog.Web/Views/Shared/Layouts/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Mike's Blog - @ViewData["Title"]</title>

    <environment include="Development">

        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">

        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="container body-content">
        <div class="row">
            <div class="col-xs-12">
                @RenderBody()
            </div>
        </div>
    </div>

    @Html.Partial("_DefaultScripts")

    @RenderSection("Scripts", required: false)
</body>
</html>

Blog.Web/Views/Shared/Layouts/_SignInLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <partial name="_DefaultHead" />
</head>
<body>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xs-12">
                @RenderBody()
            </div>
        </div>
    </div>
    <partial name="_DefaultScripts" />

    @RenderSection("Scripts", required: false)
</body>
</html>