Blog.Web/Controllers/ViewComponents/BlogPostListViewComponent.cs
using AutoMapper;
using Blog.Data.Models;
using Blog.Web.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Controllers.ViewComponents
{
    public class BlogPostListViewComponent : ViewComponent
    {
        private readonly BlogDbContext _blogContext;
        private readonly IMapper _mapper;
        private readonly ILinkUtilities _linkUtilities;

        public BlogPostListViewComponent(BlogDbContext blogContext, IMapper mapper, ILinkUtilities linkUtilities)
        {
            _blogContext = blogContext;
            _mapper = mapper;
            _linkUtilities = linkUtilities;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var dbPosts = await _blogContext
                .Posts
                .Where(c=>!c.Hidden)
                .OrderByDescending(c => c.CreationDate)
                .ToListAsync();

            var viewPosts = dbPosts.Select(c => {
                    var post = _mapper.Map<Web.ViewModels.Post>(c);
                    post.Permalink = _linkUtilities.GetPermalink(c.UrlSegment);
                    post.Path = _linkUtilities.GetPath(c.UrlSegment);
                    return post;
                }).ToList();

            foreach (var viewPost in viewPosts.Take(5))
            {
                viewPost.LatestFive = true;
            }
            
            return View("~/Views/Shared/Components/BlogPostList.cshtml", viewPosts);
        }
    }
}

Blog.Web/Controllers/ViewComponents/BlogPostSearchBoxViewComponent.cs
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Controllers.ViewComponents
{
    public class BlogPostSearchBoxViewComponent : ViewComponent
    {

        public IViewComponentResult Invoke()
        {
            return View("~/Views/Shared/Components/BlogPostSearchBox.cshtml", new SearchRequest());
        }
    }
}

Blog.Web/Views/Shared/_DefaultHead.cshtml
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>@ViewData["Title"] - Solores Software</title>

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">


<environment include="Development">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/prism.css" asp-append-version="true" />

</environment>
<environment exclude="Development">
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/prism.min.css" asp-append-version="true" />

</environment>



@Html.Raw(JavaScriptSnippet.FullScript)

Blog.Web/Views/Shared/_DefaultScripts.cshtml
    <environment include="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha384-fJU6sGmyn07b+uD1nMk7/iSb4yvaowcueiQhfVgQuD98rfva8mcr1eSvjchfpMrH" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.js" integrity="sha384-fBfC1bwVKBZ4DpQVH9W3yi63j/15oGKtzDADz5oVeLvyXlbYR+k/Eim3Qi4585S2" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.js" integrity="sha384-C8hjioqadbXfCfVhnT6NUWCL1hD9kTjwIhQ+c5Q/fVyXwav3uPly3e/0PN/X8Yd9" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js" integrity="sha384-5ALuv45P2Jsjqer94hMysQvm4H1wQy87zdXLpAubxbsHLkb8CO7FtxjfatwVdYhc" crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.js" integrity="sha384-rkSGcquOAzh5YMplX4tcXMuXXwmdF/9eRLkw/gNZG+1zYutPej7fxyVLiOgfoDgi" crossorigin="anonymous"></script>

        <script src="~/lib/tinymce/tinymce.js" asp-append-version="true"></script>

        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/prism.js" asp-append-version="true"></script>


    </environment>
    <environment exclude="Development">
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT" crossorigin="anonymous"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js" integrity="sha384-6UVI3atWyL/qZbDIJb7HW8PyHhFNMiX5rYNY2gAYcaYJjYk5cNIQShSQPBleGMYu" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js" integrity="sha384-R3vNCHsZ+A2Lo3d5A6XNP7fdQkeswQWTIPfiYwSpEP3YV079R+93YzTeZRah7f/F" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.min.js" integrity="sha384-hpW2z+6vt5klZGNoKgrK+fGNDXlKaaJTq0+GMJNW2RstoJI9gyy8vpNl7rOH8MLF" crossorigin="anonymous"></script>

        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

        <script src="~/lib/tinymce/tinymce.min.js" asp-append-version="true"></script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
        <script src="~/js/prism.min.js" asp-append-version="true"></script>
    </environment>

Blog.Web/Views/Shared/_SideBar.cshtml
<div class="sidebar mt-3">
    @await Component.InvokeAsync("BlogPostList")
    <hr />
    @await Component.InvokeAsync("BlogPostSearchBox")
    <hr />
    <div class="sidebar-links">
        <h5 class="text-center">Find me</h5>

        <ul>
            <li>
                <a href="https://stackoverflow.com/users/3910619/zola25"><img src="https://stackoverflow.com/users/flair/3910619.png?theme=clean" width="208" height="58" alt="profile for zola25 at Stack Overflow, Q&amp;A for professional and enthusiast programmers" title="profile for zola25 at Stack Overflow, Q&amp;A for professional and enthusiast programmers"></a>
            </li>
            <li>
                <a href="https://www.linkedin.com/in/mike-towill-b54ab21b"><img class="linkedin-logo" src="/images/LI-Logo.png" /></a>
            </li>
        </ul>
    </div>

</div>