Blog.Web/Controllers/ViewComponents/SelectPostsViewComponent.cs
using Blog.Data.Models;
using Blog.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;

namespace Blog.Controllers.ViewComponents
{
    public class SelectPostsViewComponent : ViewComponent
    {
        public BlogDbContext _blogContext;

        public SelectPostsViewComponent(BlogDbContext blogContext)
        {
            _blogContext = blogContext;
        }

        public IViewComponentResult Invoke(int selectedPostId)
        {
            var posts = _blogContext.Posts
                .Select(c=> new SelectListItem { Text = $"{c.Title}", Value = c.Id.ToString(), Selected = c.Id == selectedPostId })
                .ToList();

            posts.Insert(0, new SelectListItem { Text = $"Create New Post", Value = "0", Selected = selectedPostId == 0 });
            
            return View("~/Views/Shared/Components/SelectPosts.cshtml", new SelectPosts {
                BlogPosts = posts
            });;
        }
    }
}

Blog.Web/Views/Admin/Admin.cshtml
@model NewPost

<form method="post" asp-action="Admin" asp-controller="Blog">
    <div class="form-group">
        <p asp-validation-for="Title"></p>
        <label for="Title">Title</label>
        <input asp-for="Title" class="form-control" placeholder="Title">
    </div>
    <div class="form-group">
        <p asp-validation-for="Permalink"></p>
        <label for="Permalink">Permalink</label>
        <input asp-for="Permalink" class="form-control" placeholder="permalink">
    </div>
    <div class="form-group">
        <p asp-validation-for="HtmlContent"></p>
        <label for="Content">Content</label>
        <textarea asp-for="Html"></textarea>
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>



@section Scripts
{
    <script>tinymce.init({
            selector: 'textarea',
            plugins: "preview code"
        });</script>
}

Blog.Web/Views/Admin/Index.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "Layouts/_AdminLayout";
}

@model Admin

@await Component.InvokeAsync("SelectPosts", Model.PostId)

<hr />

<div class="admin-edit-post-container">
    @await Component.InvokeAsync("EditPostForm", Model.PostId)
</div>
@section scripts {

    <environment include="Development">
        <script src="~/js/editPostForm.js" asp-append-version="true"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/js/editPostForm.min.js" asp-append-version="true"></script>
    </environment>
}