Blog.Web/ViewModels/SelectPosts.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Blog.Web.ViewModels
{
    public class SelectPosts
    {
        public List<SelectListItem> BlogPosts {get;set;}

        public int PostId {get;set;}
    }

}

Blog.Web/Controllers/SearchController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Blog.Data.Models;
using AutoMapper;
using Blog.Web.Services;
using Microsoft.AspNetCore.Routing;
using Blog.Web.ViewModels;

namespace Blog.Controllers
{
    public class SearchController : Controller
    {
        private BlogDbContext _bloggingContext;
        private ISnapshotText _snapshotText;
        private IMapper _mapper;

        public SearchController(BlogDbContext blogContext, ISnapshotText snapshotText, IMapper mapper)
        {
            _bloggingContext = blogContext;
            _snapshotText = snapshotText;
            _mapper = mapper;
        }

        public IActionResult SearchRedirect(SearchRequest searchRequest)
        {
            // This prevents the problem of form resubmission when clicking back
            return RedirectToAction("SearchResults", new RouteValueDictionary(searchRequest));
        }

        public IActionResult SearchResults(SearchRequest searchRequest)
        {
            var posts = _bloggingContext
                .Posts
                .Where(c => !c.Hidden && (c.Html.Contains(searchRequest.Text) || c.Title.Contains(searchRequest.Text))).ToList();
            var searchResults = posts.Select(c => 
            new SearchResult() { 
                Post = _mapper.Map<Data.Models.Post, Web.ViewModels.Post>(c), 
                SnapshotText = _snapshotText.GetFirstNCharacters(c.Html, 200) + " ..." }
            );
            return View(searchResults);
        }

        public ActionResult CheckExistingPermalink(string permalink)
        {
            bool exists = _bloggingContext
                .Posts
                .Any(c => c.UrlSegment == permalink);

            return Json(!exists);
        }
    }
}

Blog.Web/Views/Shared/Components/BlogPostList.cshtml
@model IEnumerable<Post> 

    <div class="post-list">
        <h5 class="text-center">Articles</h5>

        <ul>
            @foreach (var blogPost in Model)
            {
                <li ><a class="post-list-item @(blogPost.LatestFive ? "latest-five" : "hidden")" href="@blogPost.Path">@blogPost.Title</a></li>
            }
            @if(Model.Count() > 5) {
                <li><a class="view-all" href="javascript::void"><i>..view all</i></a></li>
            }
        </ul>
    </div>

@section Scripts 
{
    <script type="text/javascript">
        $(document).ready(function () {
            $('.post-list .view-all').onclick(function () {
                if ($('.post-list-item.hidden').len > 0) {
                    $('.post-list-item.hidden').toggleClass("hidden");
                    $('.post-list .view-all i').text("..collapse");
                } else {
                    $('.post-list-item').not('.latest-five').toggleClass("hidden");
                    $('.post-list .view-all i').text("..view all");
                }
            });
        });
    </script>
}

Blog.Web/Views/Shared/Components/BlogPostSearchBox.cshtml
@model SearchRequest

    <div class="post-search-box">
        <h5 class="text-center">Search</h5>
        <form asp-controller="Search" asp-action="SearchRedirect">
            <div class="form-group">
                <input asp-for="Text" class="form-control" placeholder="Search articles" />
            </div>
            <input type="submit" class="btn btn-outline-secondary btn-block" value="Search" />
        </form>
    </div>

Blog.Web/Views/Shared/Components/EditPostForm.cshtml
@model EditablePost

@if(Model.NewlyCreated) {
    <div class="text-center">
        <h4 class="font-weight-bold text-success">New Post Created</h4>
    </div>
}
    <form id="admin-edit-post-form"
          data-ajax="true"
          data-ajax-method="POST"
          data-ajax-url="/admin/post/@Model.PostId"
          data-ajax-begin="editPostForm.begin"
          data-ajax-success="editPostForm.success"
          data-ajax-failure="editPostForm.failure">

        <input asp-for="PostId" type="hidden" />
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label asp-for="Title" class="input-group-text font-weight-bold">Title</label>
                </div>
                <input asp-for="Title" class="form-control" placeholder="Title">
                <span asp-validation-for="Title" class="text-warning"></span>
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label asp-for="CreationDate" class="input-group-text font-weight-bold">Creation Date</label>
                </div>
                <input asp-for="CreationDate" class="form-control" placeholder="Title">
                <span asp-validation-for="CreationDate" class="text-warning"></span>
            </div>
        </div>
        <div class="form-group">

            <div class="form-check form-check-inline">
                <label asp-for="Hidden" class="form-check-label font-weight-bold">Hidden</label>
                <input asp-for="Hidden" type="checkbox" class="form-check-input ml-2">
            </div>
        </div>
        <div class="form-group">
            <div class="input-group">
                <div class="input-group-prepend">
                    <label asp-for="UrlSegment" class="input-group-text font-weight-bold">URL Segment</label>
                </div>

                <input asp-for="UrlSegment" class="form-control" placeholder="URL segment">
                <span asp-validation-for="UrlSegment" class="text-warning"></span>
            </div>
        </div>

        <div class="mb-2">
            <button type="submit" class="btn btn-outline-success">@(Model.PostId == 0 ? "Create" : "Update")</button>

            @if(Model.PostId != 0) {
                <a href="@Model.Path" target="_blank" rel="noopener noreferrer" class="btn btn-outline-secondary">
                    View Post
                </a>
            }
            <button type="button" class="btn btn-outline-danger admin-delete-post" style="@(Model.PostId == 0 ? "display: none;" : null)">Delete</button>
        </div>
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="admin-edit-post-result" style="display: none;">

        </div>
        <div class="form-group">
            <textarea class="admin-edit-post-html" id="admin-edit-post-html" asp-for="Html"></textarea>
            <span asp-validation-for="Html" class="text-warning"></span>
        </div>
    </form>

<div class="modal admin-delete-post-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Delete this post?</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger admin-delete-post-confirm">Delete</button>
                <button type="button" class="btn btn-secondary admin-delete-post-cancel" data-dismiss="modal">Cancel</button>
            </div>
        </div>
    </div>
</div>

<div class="modal admin-delete-post-success-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Post Deleted</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary admin-delete-post-success-confirm">Ok</button>
            </div>
        </div>
    </div>
</div>

Blog.Web/Views/Shared/Components/SelectPosts.cshtml
@model SelectPosts

<div class="select-posts text-center mt-3 mb-3">
    <div class="form-group">
        <select class="form-control select-posts-selectbox" asp-for="PostId" asp-items="Model.BlogPosts"></select>
    </div>
</div>

@Html.Script(
        @<script>
            $(function () {
                $(document).on('change', '.select-posts-selectbox', function (e) {

                    $.ajax({
                        url: "/admin/post/" + parseInt(this.value),
                        method: "GET",
                        success: function (result) {
                            $('.admin-edit-post-container').html(result);
                            editPostForm.loadTinymce();

                            // https://stackoverflow.com/a/14135013/3910619
                            $("#admin-edit-post-form").removeData("validator");
                            $("#admin-edit-post-form").removeData("unobtrusiveValidation");
                            $.validator.unobtrusive.parse("#admin-edit-post-form");
                            
                        }
                    });
                });
            });
        </script>
)